database:
  host: 192.168.1.4
  port: 5432
  username: dart
  password: dart
  databaseName: heroes
assets:
  basepath: assets
  resized_path: assets/resized
  size: 768
app:
  history: 12
  clientid: nxp.app.test
  clientsecret: nxp.app.client.secret